FROM python:3.11.9-slim-bookworm

WORKDIR /code

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /code/backend

EXPOSE 5000
CMD ["python", "-m", "backend.app"]
